### ISSUE TITLE
Suggested fix

### ISSUE THREAD

**Issue by LeeTibbert** [wookietreiber/scala-native-fork#1]
Please see comments at https://github.com/scala-native/scala-native/issues/1104

Short story; IIRC execvp wants a NULL terminated args array: try adding: 

    ptr(4) = null

Hope this helps get your code working. This is an interesting code study.

Lee

**Comment by LeeTibbert** [comment]
At too early in the morning, I bolted awake with the realization
that if you are going to assign to ptr(4) you also need to increase
the alloc() to 5. Duh! 

The current fork.scala has an equivalent bug. It does an alloc(3), then
assigns to ptr(3) {which is one off the end of the allocated space.)

L.

**Comment by wookietreiber** [comment]
@LeeTibbert Thanks for your suggestions, I will try them.

Regarding assigning to `ptr(3)` for an `alloc(3)`: this is one of the weird things I recognized. I think, even if the C allows this to happen, i.e. writing to memory that does not belong to you, the compiler should issue an error or at least a warning. I wasn't aware, that the compiler does not do this at all at the moment.

**Comment by wookietreiber** [comment]
Ok, seems you're right :)

This works:

```scala
        val ptr: Ptr[CString] = alloc[CString](3)
        ptr(0) = toCString("echo")
        ptr(1) = toCString("README.md")
        ptr(2) = null
```

This also works, when I just don't touch the last one, I suppose because it's initialized with `null`:

```scala
        val ptr: Ptr[CString] = alloc[CString](3)
        ptr(0) = toCString("echo")
        ptr(1) = toCString("README.md")
```

But I suppose it might be better to explicitly set it to `null`

**Comment by wookietreiber** [comment]
Giving this a little form:

```scala
  def toCArray(a: Array[String])(implicit Z: Zone): Ptr[CString] = {
    val ptr: Ptr[CString] = alloc[CString](a.size + 1)
    var i = 0
    while (i < a.size) {
      ptr(i) = toCString(a(i))
      i += 1
    }
    ptr(a.size) = null
    ptr
  }
```

And now this works:

```scala
        val cmd = Array("echo", "a", "b")
        val ptr = toCArray(cmd)
```
